//! plugin の生成 dir（core の `PLUGIN_DIR`）の下の `.claude-plugin/plugin.json` と `hooks/hooks.json`、root の
//! `.claude-plugin/marketplace.json` を NAME と rules 行から生成する。
//!
//! manifest を手書きしないのは、名前の字面が repo へ散るのを避けるためである
//! （器 SPEC §7）。生成は冪等で、同じ workspace からは同じ bytes が出る。
//! hook の timeout は数値を焼かず rules 行 `hook.timeout_s` から読む（憲法 C1 / C5）。
//! 生成 dir は root 相対の実行時の読み（[`Layout::plugin_dir`]）で、下の定数は dir からの末尾の字面である
//! （設計 consumer-sync.md §17 形 1・結ぶのは呼び手）。

use crate::check::Layout;
use crate::toml_lite;
use std::fs;
use std::path::Path;

/// plugin manifest の相対 path（生成 dir 相対）。
pub const MANIFEST_REL: &str = ".claude-plugin/plugin.json";

/// hook manifest の相対 path（生成 dir 相対）。
pub const HOOKS_REL: &str = "hooks/hooks.json";

/// marketplace manifest の相対 path（root 相対）。
pub const MARKETPLACE_REL: &str = ".claude-plugin/marketplace.json";

/// 規則の値の正本の相対 path。
pub const RULES_REL: &str = "rules/manifest.toml";

/// hook 1 回の timeout（秒）を持つ rules 行。
pub const ROW_TIMEOUT: &str = "hook.timeout_s";

/// `PreToolUse` で見る tool の matcher。**`Bash` を含む**（席の権能の Bash 面・設計 seat-roles.md §4・
/// `s2-07l.201`）: write-set guard と cap guard は `Bash` を見ないまま（core 側の集合が決める）で、role guard
/// だけが command 行を読む。末尾の `AskUserQuestion` は選択式の問いの道具を役割を解く前に止める 1 関数へ届ける
/// （設計 vessel-hook.md §20・ADR-0084）。
const MATCHER: &str = "Bash|Edit|Write|MultiEdit|NotebookEdit|AskUserQuestion";

/// `SessionStart` に紐づく subcommand。
const SUB_SESSION_START: &str = "session-start";

/// `PreToolUse` に紐づく subcommand。
const SUB_PRE_TOOL_USE: &str = "pre-tool-use";

/// `PermissionRequest` で見る tool の matcher（**`Bash` だけ**）。
///
/// 内蔵 guard の問いに答えるのは `Bash` の周に限る。広げると器が答える筋合いの無い
/// 承認まで機械が deny することになる。
const MATCHER_PERMISSION: &str = "Bash";

/// `PermissionRequest` に紐づく subcommand。
const SUB_PERMISSION_REQUEST: &str = "permission-request";

/// `UserPromptSubmit` に紐づく subcommand（席の状態の打刻 = Busy・設計 seat-state.md §2）。
const SUB_USER_PROMPT_SUBMIT: &str = "user-prompt-submit";

/// `Stop` に紐づく subcommand（席の状態の打刻 = Idle）。
const SUB_STOP: &str = "stop";

/// `PreCompact` に紐づく subcommand（圧縮の直前の 1 枠・設計 seat-roles.md §22・`s2-07l.489`）。matcher は付けない
/// （`manual` / `auto` の両方で撃つ・弁別は payload の `trigger` を器が読む）。
const SUB_PRE_COMPACT: &str = "pre-compact";

/// hook に自席の pane id を渡す引数（ADR-0015 §2.2）。**全 entry が持つ**: 打刻の席と記録の
/// `seat` 列は同じ pane id から解く（`s2-07l.150`）。
///
/// `$TMUX_PANE` の展開は **Claude Code が hook を起動する shell** が行う（`${<NAME_UPPER>_BIN}`
/// と同じ場所・同じ生成器）。core は env を読まず、typed な引数 `--pane` で受ける。`--tmux-socket`
/// は付けない（既定の server）。
const PANE_ARG: &str = " --pane \\\"$TMUX_PANE\\\"";

/// hook に session の起動 dir（anchor）を渡す引数（設計 seat-roles.md §4・`s2-07l.201`）。**全 entry が持つ**:
/// repo root・`served`・state dir はこの dir から解き、席が `cd` しても変わらない（run 2 の lens FAIL の穴）。
///
/// `$CLAUDE_PROJECT_DIR` の展開も Claude Code が hook を起動する shell が行う（[`PANE_ARG`] と同型）。
const PROJECT_ARG: &str = " --project \\\"$CLAUDE_PROJECT_DIR\\\"";

/// hook に plugin の root（hooks.json の在る場所）を渡す引数（設計 consumer-sync.md §3・`s2-07l.303`）。**全 entry が
/// 持つ**: `session-start` が読み込み元の記録（`seat/<target>/plugin`）に写す。値が空の周（plugin の外から撃った hook）
/// は器が記録しない。`$CLAUDE_PLUGIN_ROOT` の展開も hook を起動する shell が行う（[`PANE_ARG`] と同型）。
const PLUGIN_ROOT_ARG: &str = " --plugin-root \\\"$CLAUDE_PLUGIN_ROOT\\\"";

/// plugin の説明文。**2 つの manifest が同じ 1 箇所から出す**（写して持つと片方だけ動く）。
fn description(name: &str) -> String {
    format!("{name} plugin manifest (generated by cargo xtask gen-manifest)")
}

/// `name` / `version` / `description` の 3 key を持つ manifest 本文を組み立てる。
pub fn render(name: &str, version: &str) -> String {
    let description = description(name);
    format!("{{\n  \"name\": \"{name}\",\n  \"version\": \"{version}\",\n  \"description\": \"{description}\"\n}}\n")
}

/// `name` / `description` / `owner` / `plugins` の 4 key を持つ marketplace 本文を組み立てる。
///
/// **個人の handle・repo の URL・host の path・口座名を 1 文字も持たない**（本 repo は
/// PUBLIC・SRS CON2）。`owner.url` は任意の field なので**置かない**——置けるものを置くと、
/// 生成器が個人情報を repo へ流し込む常設の口になる。`source` を `./<plugin_dir>` に取るのは、この
/// repo の生成 dir だけを directory marketplace の plugin として読ませるためで（install の写しの単位を
/// plugin に閉じる・設計 consumer-sync.md §17・ADR-0038）、絶対 path を書かずに済む形でもある。
/// marketplace 自身の `description` は `claude plugin validate` が見る key で、plugins 側と
/// 同じ共有 [`description`] から出す（`author` は個人情報になりうるので足さない・A1）。
pub fn render_marketplace(name: &str, plugin_dir: &str) -> String {
    let description = description(name);
    format!(
        "{{\n  \"name\": \"{name}\",\n  \"description\": \"{description}\",\n  \"owner\": {{\n    \"name\": \"{name}\"\n  }},\n  \"plugins\": [\n    {{\n      \"name\": \"{name}\",\n      \"source\": \"./{plugin_dir}\",\n      \"description\": \"{description}\"\n    }}\n  ]\n}}\n"
    )
}

/// hook が起動するコマンドの字面。
///
/// `${<NAME_UPPER>_BIN:-<NAME>}` の展開は **Claude Code が hook を起動する shell**
/// が行う。器そのものは env を 1 つも読まない（憲法 C2.2・ADR-0004 §2.4）。
fn command(name: &str, sub: &str) -> String {
    format!("\\\"${{{}_BIN:-{name}}}\\\" hook {sub}{PANE_ARG}{PROJECT_ARG}{PLUGIN_ROOT_ARG}", name.to_uppercase())
}

/// 1 event 分の材料。
struct Hook<'a> {
    /// Claude Code の event 名。
    event: &'a str,
    /// tool の matcher（無ければ全 tool）。
    matcher: Option<&'a str>,
    /// 紐づく subcommand。
    sub: &'a str,
}

/// 1 event 分の entry を組む。
fn entry(hook: &Hook, name: &str, timeout: u64) -> String {
    let head = match hook.matcher {
        Some(found) => format!("        \"matcher\": \"{found}\",\n"),
        None => String::new(),
    };
    format!(
        "    \"{}\": [\n      {{\n{head}        \"hooks\": [\n          {{\n            \"type\": \"command\",\n            \"command\": \"{}\",\n            \"timeout\": {timeout}\n          }}\n        ]\n      }}\n    ]",
        hook.event,
        command(name, hook.sub)
    )
}

/// hooks.json 本文を組み立てる（entry は 6 つ・timeout は rules 行を写す）。
pub fn render_hooks(name: &str, timeout: u64) -> String {
    let hooks = [
        Hook { event: "SessionStart", matcher: None, sub: SUB_SESSION_START },
        Hook { event: "PreToolUse", matcher: Some(MATCHER), sub: SUB_PRE_TOOL_USE },
        Hook { event: "PermissionRequest", matcher: Some(MATCHER_PERMISSION), sub: SUB_PERMISSION_REQUEST },
        Hook { event: "UserPromptSubmit", matcher: None, sub: SUB_USER_PROMPT_SUBMIT },
        Hook { event: "Stop", matcher: None, sub: SUB_STOP },
        Hook { event: "PreCompact", matcher: None, sub: SUB_PRE_COMPACT },
    ];
    let entries: Vec<String> = hooks.iter().map(|hook| entry(hook, name, timeout)).collect();
    format!("{{\n  \"hooks\": {{\n{}\n  }}\n}}\n", entries.join(",\n"))
}

/// rules manifest から `id` の行の `value` を整数で引く。
///
/// `[[rule]]` は array-of-tables なので、section 行で block を切り替えながら
/// 「いま読んでいる block の id」を追う（file 全体の行 grep はしない）。
pub fn rule_int(text: &str, id: &str) -> Result<u64, String> {
    let mut current: Option<String> = None;
    for line in text.lines() {
        if toml_lite::section_header(line).is_some() {
            current = None;
            continue;
        }
        let Some((key, raw)) = toml_lite::key_value(line) else {
            continue;
        };
        if key == "id" {
            current = toml_lite::quoted(raw);
        }
        if key == "value" && current.as_deref() == Some(id) {
            return raw
                .parse::<u64>()
                .map_err(|err| format!("{id} の value が整数でない（{raw}・{err}）"));
        }
    }
    Err(format!("{id} が {RULES_REL} に無い"))
}

/// `root` 配下の 1 file を親 dir ごと書き出す。
fn write_under(root: &Path, rel: &str, body: &str) -> Result<String, String> {
    let path = root.join(rel);
    let dir = path
        .parent()
        .ok_or_else(|| format!("{} の親 dir が無い", path.display()))?;
    fs::create_dir_all(dir).map_err(|err| format!("{} を作れない: {err}", dir.display()))?;
    fs::write(&path, body).map_err(|err| format!("{} を書けない: {err}", path.display()))?;
    Ok(path.display().to_string())
}

/// workspace `root` の plugin manifest と hook manifest（生成 dir の下）と marketplace（root）を生成して書き出し、
/// 報告行を返す。生成 dir の定数が core に無い周は 1 file も書かずに断る。
pub fn generate(root: &Path) -> Result<String, String> {
    let layout = Layout::discover(root)?;
    let version = layout.core_version()?;
    let plugin_dir = layout.plugin_dir()?;
    let rules = fs::read_to_string(root.join(RULES_REL))
        .map_err(|err| format!("{RULES_REL} を読めない: {err}"))?;
    let timeout = rule_int(&rules, ROW_TIMEOUT)?;
    let payload = root.join(&plugin_dir);
    let plugin = write_under(&payload, MANIFEST_REL, &render(&layout.name, &version))?;
    let hooks = write_under(&payload, HOOKS_REL, &render_hooks(&layout.name, timeout))?;
    let market = write_under(root, MARKETPLACE_REL, &render_marketplace(&layout.name, &plugin_dir))?;
    Ok(format!(
        "xtask gen-manifest: wrote {plugin}, {hooks} and {market} (name={} version={version} timeout={timeout}s)",
        layout.name
    ))
}

#[cfg(test)]
mod tests {
    use super::{
        generate, render, render_hooks, render_marketplace, rule_int, HOOKS_REL, MANIFEST_REL,
        MARKETPLACE_REL, ROW_TIMEOUT, RULES_REL,
    };
    use crate::check::{json_string_field, Layout};
    use std::path::{Path, PathBuf};
    use std::sync::atomic::{AtomicU32, Ordering};
    use std::time::{SystemTime, UNIX_EPOCH};

    /// 同一 process 内での dir 名衝突を避ける連番（`cargo test` は thread 並走）。
    static SEQ: AtomicU32 = AtomicU32::new(0);

    /// fixture の NAME。**実在しない名**にする（生成器が字面を焼く変異は、この名が出力に
    /// 現れないことで落ちる）。
    const FIXTURE_NAME: &str = "fixturename";
    /// fixture の core version。
    const FIXTURE_VERSION: &str = "9.9.9";
    /// fixture の hook timeout（rules 行）。tracked の値と違えて「読んでいる」ことを測る。
    const FIXTURE_TIMEOUT: u64 = 7;
    /// fixture の生成 dir（core の `PLUGIN_DIR`）。tracked の値と違えて「core から読んでいる」ことを測る。
    const FIXTURE_PLUGIN_DIR: &str = "fixture-payload";

    /// repo の外に一意な tmp dir を作る（`tempfile` は足さない・憲法 A3）。
    /// `create_dir`（`_all` ではない）で既存 dir を衝突として検出し、連番を変えて取り直す。
    fn make_tmp_dir() -> PathBuf {
        let base = std::env::temp_dir();
        for _ in 0..8 {
            let nanos = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map(|d| d.subsec_nanos())
                .unwrap_or(0);
            let seq = SEQ.fetch_add(1, Ordering::Relaxed);
            let dir = base.join(format!("genmanifest-{}-{nanos}-{seq}", std::process::id()));
            if std::fs::create_dir(&dir).is_ok() {
                return dir;
            }
        }
        panic!("一意な tmp dir を 8 回で作れない");
    }

    /// `generate` が読む最小の workspace を tmp に組む（Cargo.toml・core crate・runner・rules）。
    fn write_fixture_root() -> PathBuf {
        let root = write_fixture_root_without_plugin_dir();
        std::fs::write(
            root.join("crates/core/src/name.rs"),
            format!("pub const NAME: &str = \"{FIXTURE_NAME}\";\npub const PLUGIN_DIR: &str = \"{FIXTURE_PLUGIN_DIR}\";\n"),
        )
        .expect("name.rs を書ける");
        root
    }

    /// [`write_fixture_root`] から core の `PLUGIN_DIR` だけを欠いた workspace（定数の無い core）。
    fn write_fixture_root_without_plugin_dir() -> PathBuf {
        let root = make_tmp_dir();
        let write = |rel: &str, body: &str| {
            let path = root.join(rel);
            std::fs::create_dir_all(path.parent().expect("親 dir")).expect("dir を作れる");
            std::fs::write(&path, body).expect("fixture を書ける");
        };
        write(
            "Cargo.toml",
            "[workspace]\nmembers = [\"crates/core\", \"crates/xtask\"]\n",
        );
        write(
            "crates/core/Cargo.toml",
            &format!("[package]\nname = \"core\"\nversion = \"{FIXTURE_VERSION}\"\n"),
        );
        write(
            "crates/core/src/name.rs",
            &format!("pub const NAME: &str = \"{FIXTURE_NAME}\";\n"),
        );
        write("crates/xtask/Cargo.toml", "[package]\nname = \"xtask\"\n");
        write(
            RULES_REL,
            &format!("[[rule]]\nid = \"{ROW_TIMEOUT}\"\nvalue = {FIXTURE_TIMEOUT}\n"),
        );
        root
    }

    /// tmp root の生成物を読む。
    fn read_generated(root: &Path, rel: &str) -> String {
        std::fs::read_to_string(root.join(rel)).unwrap_or_else(|err| panic!("{rel} を読める: {err}"))
    }

    /// 生成 dir の下の生成物を読む（`PLUGIN_DIR` 相対の 2 file）。
    fn read_payload(root: &Path, rel: &str) -> String {
        read_generated(&root.join(FIXTURE_PLUGIN_DIR), rel)
    }

    /// `generate(root)` の**書く経路**: 3 つの manifest が実際に書かれ、render の返り値と byte
    /// 一致する（既存の 2 本は tracked 生成物との一致しか見ず、書く経路は無測定だった）。
    #[test]
    fn gen_manifest_writes_all_three_manifests_via_generate() {
        let root = write_fixture_root();
        for rel in [MANIFEST_REL, HOOKS_REL] {
            assert!(!root.join(FIXTURE_PLUGIN_DIR).join(rel).exists(), "生成前に {rel} は無い");
        }
        assert!(!root.join(MARKETPLACE_REL).exists(), "生成前に marketplace は無い");

        let report = generate(&root).expect("fixture の workspace から生成できる");
        // 後始末は assert より前に済ませる（赤い回に tmp を漏らさない・check.rs の作法と同じ）。
        let (plugin, hooks, market) = (
            read_payload(&root, MANIFEST_REL),
            read_payload(&root, HOOKS_REL),
            read_generated(&root, MARKETPLACE_REL),
        );
        std::fs::remove_dir_all(&root).ok();

        assert_eq!(plugin, render(FIXTURE_NAME, FIXTURE_VERSION), "plugin.json は render の bytes そのもの");
        assert_eq!(
            hooks,
            render_hooks(FIXTURE_NAME, FIXTURE_TIMEOUT),
            "hooks.json は render_hooks の bytes そのもの（timeout は fixture の rules 行）"
        );
        assert_eq!(
            market,
            render_marketplace(FIXTURE_NAME, FIXTURE_PLUGIN_DIR),
            "marketplace.json は render_marketplace の bytes そのもの"
        );
        assert!(
            report.contains(&format!("name={FIXTURE_NAME} version={FIXTURE_VERSION} timeout={FIXTURE_TIMEOUT}s")),
            "報告行は fixture の値を写す（tracked の値ではない）: {report}"
        );
        // 実在の名は tracked の workspace から読む（歯の source に字面を置かない・name-literal）。
        let real = Layout::discover(&workspace_root()).expect("workspace の配置を読める").name;
        assert!(
            !hooks.contains(&real),
            "生成器は実在の名（{real}）を焼いていない（fixture の名だけが出る）"
        );
    }

    /// 共有 `description(name)` が plugin.json と marketplace.json の**両方**へ届く: marketplace
    /// 自身の description（plugins の前・`claude plugin validate` が見る key）と plugin.json の
    /// description が同一 ∧ 非空 ∧ NAME を含む。A/B: description() の文言を変えると両面の期待が
    /// 同時に動く（片方だけ写して持つ形をこの歯は通さない）。
    #[test]
    fn gen_manifest_shared_description_reaches_both_manifests_via_generate() {
        let root = write_fixture_root();
        generate(&root).expect("fixture の workspace から生成できる");
        let plugin = read_payload(&root, MANIFEST_REL);
        let market = read_generated(&root, MARKETPLACE_REL);
        // 後始末は assert より前（赤い回に tmp を漏らさない）。
        std::fs::remove_dir_all(&root).ok();

        let in_plugin = json_string_field(&plugin, "description").expect("plugin.json に description");
        let market_head = market
            .split_once("\"plugins\"")
            .map(|(head, _)| head.to_owned())
            .expect("marketplace.json に plugins");
        let in_market = json_string_field(&market_head, "description")
            .expect("marketplace 自身（plugins の前）に description が在る");
        assert!(!in_plugin.is_empty(), "非空");
        assert_eq!(in_plugin, in_market, "2 つの manifest の description は同じ 1 箇所から出る");
        assert!(in_market.contains(FIXTURE_NAME), "description は NAME を含む: {in_market}");
        let (_, market_tail) = market.split_once("\"plugins\"").expect("plugins");
        assert_eq!(
            json_string_field(market_tail, "description").as_deref(),
            Some(in_market.as_str()),
            "plugins[0] の description も同じ 1 箇所から出る"
        );
    }

    /// workspace root（この crate の 2 つ上）。
    fn workspace_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
    }

    /// tracked な生成 dir（workspace root + core の `PLUGIN_DIR`）。
    fn tracked_payload(layout: &Layout) -> PathBuf {
        layout.root.join(layout.plugin_dir().expect("core に PLUGIN_DIR が在る"))
    }

    /// 6 つの command 行がすべて `--pane`（打刻の席と記録の `seat` 列・`s2-07l.150`）→ `--project`（anchor・
    /// seat-roles.md §4・`s2-07l.201`）→ `--plugin-root`（読み込み元の記録・consumer-sync.md §3・`s2-07l.303`）を
    /// **この順で**受けて閉じる。件数（6）と subcommand ごとの形（1 つずつ）の両方で測る。
    fn assert_every_command_line_carries_the_seat_args(tracked: &str) {
        let pane_arg = " --pane \\\"$TMUX_PANE\\\"";
        let project_arg = " --project \\\"$CLAUDE_PROJECT_DIR\\\"";
        let plugin_root_arg = " --plugin-root \\\"$CLAUDE_PLUGIN_ROOT\\\"";
        for arg in [pane_arg, project_arg, plugin_root_arg] {
            assert_eq!(tracked.matches(arg).count(), 6, "hook の command 行 6 つに{arg} が付く");
        }
        for sub in ["session-start", "pre-tool-use", "permission-request", "user-prompt-submit", "stop", "pre-compact"] {
            assert_eq!(
                tracked.matches(&format!("hook {sub}{pane_arg}{project_arg}{plugin_root_arg}\"")).count(),
                1,
                "{sub} の command 行が --pane → --project → --plugin-root の順で受けて閉じる"
            );
        }
    }

    /// tracked な hooks.json が render の bytes と一致し、timeout が rules 行を写す。
    ///
    /// 生成物を手で直すと落ちる（手書き禁止の歯）。同じ入力から 2 回 render しても
    /// 同じ bytes であることも同時に測る（冪等）。
    #[test]
    fn gen_manifest_hooks_json_is_idempotent() {
        let root = workspace_root();
        let layout = Layout::discover(&root).expect("workspace の配置を読める");
        let rules = std::fs::read_to_string(root.join(RULES_REL)).expect("rules manifest を読める");
        let timeout = rule_int(&rules, ROW_TIMEOUT).expect("hook.timeout_s を引ける");
        let rendered = render_hooks(&layout.name, timeout);
        let tracked = std::fs::read_to_string(tracked_payload(&layout).join(HOOKS_REL)).expect("hooks.json を読める");

        assert_eq!(rendered, tracked, "tracked な hooks.json は生成物と同じ bytes である");
        assert_ne!(
            render_hooks(&layout.name, timeout + 1),
            rendered,
            "render は引数の timeout を実際に使う（値を焼いていない）"
        );
        assert!(
            tracked.contains(&format!("\"timeout\": {timeout}")),
            "timeout は rules 行 {ROW_TIMEOUT} の値（{timeout}）を写す"
        );
        assert_eq!(
            tracked.matches("\"type\": \"command\"").count(),
            6,
            "entry は SessionStart / PreToolUse / PermissionRequest / UserPromptSubmit / Stop / PreCompact の 6 つである"
        );
        // **数だけでなく名前で**測る。件数だけだと、event 名を取り違えた生成物
        // （同じ event を 6 回書く等）が同じ 6 で通る。
        for event in ["SessionStart", "PreToolUse", "PermissionRequest", "UserPromptSubmit", "Stop", "PreCompact"] {
            assert_eq!(
                tracked.matches(&format!("\"{event}\": [")).count(),
                1,
                "{event} の entry がちょうど 1 つ在る"
            );
        }
        assert_every_command_line_carries_the_seat_args(&tracked);
        // PreToolUse の matcher は Bash を含み（role guard の Bash 面）末尾に AskUserQuestion を持ち（§20）、PermissionRequest の matcher は不変。
        assert_eq!(
            tracked.matches("\"matcher\": \"Bash|Edit|Write|MultiEdit|NotebookEdit|AskUserQuestion\"").count(),
            1,
            "PreToolUse の matcher は Bash を含み末尾が AskUserQuestion"
        );
        assert_eq!(tracked.matches("\"matcher\": \"Bash\"").count(), 1, "PermissionRequest の matcher は Bash だけのまま");
    }

    /// 生成 hooks.json の `PreCompact` の行（圧縮の直前の 1 枠・設計 seat-roles.md §22・`s2-07l.489`）が `--pane` と
    /// `--project` を運ぶ: entry はちょうど 1 つ・matcher を持たない（`manual` / `auto` の両方で撃つ）・command 行は
    /// `hook pre-compact --pane "$TMUX_PANE" --project "$CLAUDE_PROJECT_DIR" …` の形で他の行と同じ生成器から出る
    /// （render の bytes == tracked は `gen_manifest_hooks_json_is_idempotent` が測る）。
    #[test]
    fn gen_manifest_hooks_json_precompact_entry_carries_pane_and_project() {
        let root = workspace_root();
        let layout = Layout::discover(&root).expect("workspace の配置を読める");
        let tracked = std::fs::read_to_string(tracked_payload(&layout).join(HOOKS_REL)).expect("hooks.json を読める");
        let pane_arg = " --pane \\\"$TMUX_PANE\\\"";
        let project_arg = " --project \\\"$CLAUDE_PROJECT_DIR\\\"";
        assert_eq!(tracked.matches("\"PreCompact\": [").count(), 1, "PreCompact の entry はちょうど 1 つ: {tracked}");
        assert_eq!(
            tracked.matches(&format!("hook pre-compact{pane_arg}{project_arg}")).count(),
            1,
            "PreCompact の command 行が --pane → --project を運ぶ: {tracked}"
        );
        let (_, tail) = tracked.split_once("\"PreCompact\": [").expect("PreCompact の entry");
        assert!(!tail.contains("\"matcher\""), "PreCompact は matcher を持たない（manual / auto の両方で撃つ）: {tail}");
        assert!(tail.contains(&format!("\\\"${{{}_BIN:-{}}}\\\" hook pre-compact", layout.name.to_uppercase(), layout.name)),
            "command 行は他の entry と同じ `${{NAME_BIN:-NAME}}` の形: {tail}");
        // 生成器の側: PreCompact を落とした render は tracked と一致しない（行は生成器から出ている）。
        let rules = std::fs::read_to_string(root.join(RULES_REL)).expect("rules manifest を読める");
        let timeout = rule_int(&rules, ROW_TIMEOUT).expect("hook.timeout_s を引ける");
        let rendered = render_hooks(&layout.name, timeout);
        assert_eq!(rendered.matches("hook pre-compact").count(), 1, "render も PreCompact の行を 1 つ持つ");
        assert!(rendered.ends_with("    ]\n  }\n}\n"), "PreCompact は末尾の entry: {rendered}");
    }

    /// tracked な plugin.json が render の bytes と一致する（手書き禁止・冪等・`s2-07l.104`）。
    ///
    /// 生成物 3 つのうちこれだけ「tracked == render」の歯が無く、plugin.json の drift だけが
    /// 静かに通る穴だった（`.52` lens F3）。version の出所は `generate` と同じ
    /// `Layout::core_version`（新しい読み口を作らない）。
    // flip-check: retroactive s2-07l.104
    #[test]
    fn gen_manifest_plugin_json_is_idempotent() {
        let root = workspace_root();
        let layout = Layout::discover(&root).expect("workspace の配置を読める");
        let version = layout.core_version().expect("core の version を読める");
        let rendered = render(&layout.name, &version);
        let tracked = std::fs::read_to_string(tracked_payload(&layout).join(MANIFEST_REL)).expect("plugin.json を読める");

        assert_eq!(rendered, tracked, "tracked な plugin.json は生成物と同じ bytes である");
        assert_eq!(render(&layout.name, &version), rendered, "同じ入力からは同じ bytes（冪等）");
        assert_ne!(render("other-name", &version), rendered, "render は引数の name を実際に使う");
        assert_ne!(render(&layout.name, "0.0.0-other"), rendered, "render は引数の version を実際に使う");
        assert!(
            tracked.contains(&format!("\"version\": \"{version}\"")),
            "version は core の Cargo.toml の値（{version}）を写す"
        );
    }

    /// tracked な marketplace.json が render の bytes と一致する（手書き禁止・冪等）。
    #[test]
    fn gen_manifest_marketplace_json_is_idempotent() {
        let root = workspace_root();
        let layout = Layout::discover(&root).expect("workspace の配置を読める");
        let plugin_dir = layout.plugin_dir().expect("core に PLUGIN_DIR が在る");
        let rendered = render_marketplace(&layout.name, &plugin_dir);
        let tracked =
            std::fs::read_to_string(root.join(MARKETPLACE_REL)).expect("marketplace.json を読める");

        assert_eq!(
            rendered, tracked,
            "tracked な marketplace.json は生成物と同じ bytes である"
        );
        assert_eq!(
            render_marketplace(&layout.name, &plugin_dir),
            rendered,
            "同じ入力からは同じ bytes（冪等）"
        );
        assert_ne!(
            render_marketplace("other-name", &plugin_dir),
            rendered,
            "render は引数の name を実際に使う（字面を焼いていない）"
        );
        assert_eq!(
            tracked.matches(&format!("\"source\": \"./{plugin_dir}\"")).count(),
            1,
            "source はちょうど 1 回（生成 dir を指す）: {tracked}"
        );
        let plugins = tracked
            .split_once("\"plugins\"")
            .map_or_else(String::new, |(_, tail)| tail.to_owned());
        assert_eq!(
            plugins
                .matches(&format!("\"name\": \"{}\"", layout.name))
                .count(),
            1,
            "plugins が名指す plugin はちょうど 1 件: {plugins}"
        );
        assert!(
            tracked.ends_with("}\n") && !tracked.ends_with("\n\n"),
            "末尾改行は 1 つ: {tracked:?}"
        );
    }

    /// (a・形 1) 生成 dir の名は core の `name.rs` の `PLUGIN_DIR` から読んで配置の型に載る: fixture の core の値がそのまま
    /// 出て（xtask 側に字面を持たない）、tracked の core の値の dir には生成物の 2 file が在る。
    #[test]
    fn plugin_payload_layout_reads_the_dir_from_the_core_constant() {
        let root = write_fixture_root();
        let got = Layout::discover(&root).and_then(|layout| layout.plugin_dir());
        std::fs::remove_dir_all(&root).ok();
        assert_eq!(got.as_deref(), Ok(FIXTURE_PLUGIN_DIR), "fixture の core の PLUGIN_DIR を読む");

        let layout = Layout::discover(&workspace_root()).expect("workspace の配置を読める");
        let tracked = layout.plugin_dir().expect("tracked の core に PLUGIN_DIR が在る");
        assert_ne!(tracked, FIXTURE_PLUGIN_DIR, "tracked の値は fixture と別");
        assert!(!tracked.is_empty() && !tracked.contains('/'), "root 直下の 1 dir 名: {tracked}");
        for rel in [MANIFEST_REL, HOOKS_REL] {
            assert!(layout.root.join(&tracked).join(rel).is_file(), "{tracked}/{rel} が tracked に在る");
        }
    }

    /// (a・否定の枝) `PLUGIN_DIR` の無い core は配置の読みで断られ、`generate` は 1 file も書かない（推測で root へ倒さない）。
    #[test]
    fn plugin_payload_core_without_the_constant_is_refused() {
        let root = write_fixture_root_without_plugin_dir();
        let layout = Layout::discover(&root).expect("NAME だけの core でも配置は読める");
        let refused = layout.plugin_dir();
        let generated = generate(&root);
        let written: Vec<&str> =
            [MANIFEST_REL, HOOKS_REL, MARKETPLACE_REL].into_iter().filter(|rel| root.join(rel).exists()).collect();
        std::fs::remove_dir_all(&root).ok();
        let reason = refused.expect_err("定数の無い core は断る");
        assert!(reason.contains("PLUGIN_DIR"), "断りは定数を名指す: {reason}");
        assert_eq!(generated.err().as_deref(), Some(reason.as_str()), "generate も同じ理由で断る");
        assert!(written.is_empty(), "断った周は何も書かない: {written:?}");
    }

    /// (b・形 2) `generate` は 3 file を書き、plugin.json と hooks.json は生成 dir の下・marketplace は root の
    /// `.claude-plugin/` で `source` が生成 dir を指す。root 直下の旧 path には何も書かれない（**否定の枝**）。
    #[test]
    fn plugin_payload_generate_writes_under_the_dir_and_nothing_at_the_old_paths() {
        let root = write_fixture_root();
        let report = generate(&root).expect("fixture の workspace から生成できる");
        let payload = root.join(FIXTURE_PLUGIN_DIR);
        let under: Vec<bool> = [MANIFEST_REL, HOOKS_REL].iter().map(|rel| payload.join(rel).is_file()).collect();
        let old: Vec<bool> = [MANIFEST_REL, HOOKS_REL].iter().map(|rel| root.join(rel).exists()).collect();
        let old_hooks_dir = root.join("hooks").exists();
        let market = read_generated(&root, MARKETPLACE_REL);
        let stray = payload.join(MARKETPLACE_REL).exists();
        std::fs::remove_dir_all(&root).ok();
        assert_eq!(under, [true, true], "2 file は生成 dir の下: {report}");
        assert_eq!(old, [false, false], "root 直下の旧 path には書かない");
        assert!(!old_hooks_dir, "root 直下に hooks/ を作らない");
        assert!(!stray, "marketplace は生成 dir の下に書かない");
        assert_eq!(market.matches(&format!("\"source\": \"./{FIXTURE_PLUGIN_DIR}\"")).count(), 1, "source は生成 dir: {market}");
        assert_eq!(market.matches("\"source\"").count(), 1, "source は 1 つだけ: {market}");
    }

    /// (b・否定の枝) tracked の root 直下の旧 path 2 つは消えている（生成物として再び現れない）。
    #[test]
    fn plugin_payload_tracked_old_paths_are_gone() {
        let root = workspace_root();
        for rel in [MANIFEST_REL, HOOKS_REL] {
            assert!(!root.join(rel).exists(), "root 直下の {rel} は消えている");
        }
        assert!(root.join(MARKETPLACE_REL).is_file(), "marketplace は root に残る");
    }
}
